version: 0.0
os: linux
files:
  - source: /
    destination: /var/lib/codedeploy-apps/weblate.hexxy.media
file_exists_behavior: OVERWRITE
hooks:
  ApplicationStop:
    - location: hooks/ApplicationStop.sh
      timeout: 60
  AfterInstall:
    - location: hooks/AfterInstall.sh
      timeout: 120
  ApplicationStart:
    - location: hooks/ApplicationStart.sh
      timeout: 240
